### PR TITLE
Add `declare` keyword to ClassDeclaration nodes if it is not presented yet

### LINKED ISSUE #43: Add 'declare' to classes
Hi Evgeniy,

Some of the .d.ts files I am using have classes declared without the use of the `declare` keyword:
```js
class Bounds {
	x1: number;
	y1: number;
	x2: number;
	y2: number;
}
```
TypeScript does not seem to have any issue with these when they are in module files. However, after generating with dts-bundle-generator, TypeScript is not as forgiving??

image

So, perhaps you might always emit the `declare` keyword if it is not already present on `class`es.

### PR DESCRIPTION
**Pull request by timocov**
Fixes #43

### CODE REVIEW

**Comment by aleclarson** [comment]
TypeScript allows the same lack of `declare` for `const` and `function` too.

**Comment by timocov** [comment]
@aleclarson yeah, you're right! Do you wish a make PR?

**Comment by timocov** [comment]
@aleclarson I just created #92 for that. If you wish, you can make a PR, or I can do this on the weekend.

**Comment by timocov** [comment]
Hey @aleclarson did you faced this issue? I just tested it and it looks like this it works as expected even without fix.

**Comment by timocov** [comment]
@aleclarson maybe you have a code when the compiler generates `export function name`/`export var name`/`export let`/`export const` instead of `export declare ...` (just `export` without `declare` keyword)?

**Pull request merged**
