### PR TITLE
Fixed path of an entry file if tsconfig is outside of cwd and path is relative

### PR DESCRIPTION
**Pull request by bluelovers**

### CODE REVIEW

**Comment by timocov** [comment]
Hi there, @bluelovers do you have example what does your change fix?

**Comment by timocov** [comment]
I'm going to close the PR. If you'll have any question or updates - feel free to ping me.

**Comment by bluelovers** [comment]
> Hi there, @bluelovers do you have example what does your change fix?

when use `dts-bundle-generator` in monorepo and tsconfig in root dir

> Error: Cannot find config file for file src/index.ts

this pr will fix this issues

**Comment by timocov** [comment]
> when use dts-bundle-generator in monorepo and tsconfig in root dir

Could you provide an example please? If you don't have any in public, probably you could create a repro?

**Comment by bluelovers** [comment]
[dts-bundle-generator-171.zip](https://github.com/timocov/dts-bundle-generator/files/7575514/dts-bundle-generator-171.zip)

go to `packages/pull-171`

> yarn run build 

image

**Comment by timocov** [comment]
@bluelovers thanks a lot for this example and your patience! I can see the issue now and your fix looks legit for me!

**Comment by timocov** [comment]
Released in v6.1.0 https://github.com/timocov/dts-bundle-generator/releases/tag/v6.1.0

**Pull request merged**
