### PR TITLE
Fixed issue with unknown extension when using `allowArbitraryExtensions` compiler option

### PR DESCRIPTION
**Pull request by stepankuzmin**
Skip files with unknown extensions. Otherwise, `dts-bundle-generator` will throw on `.d.json.ts` files because it doesn't support [overriding the type of a JSON file](https://www.totaltypescript.com/override-the-type-of-a-json-file).

### CODE REVIEW

**Review by timocov — CHANGES_REQUESTED** [review]
Thanks for your contribution! Please add a test case for this change, see https://github.com/timocov/dts-bundle-generator/tree/master/tests/e2e

**Comment by timocov** [comment]
https://github.com/timocov/dts-bundle-generator/tree/master/tests/e2e/test-cases/allow-js could be a good example of what you'd need to have.

**Comment by stepankuzmin** [comment]
@timocov sure! Added in 4ec8de6cf46df3937ec9d99e3803242771566e67

**Comment by timocov** [comment]
@stepankuzmin are you sure this fix fixes your problem? I just tried to run your test case against the version without your changes and it just works... Do you have a repro that I can take a look at?

**Comment by timocov** [comment]
It seems changing extension of an entry file from `.ts` to `.d.ts` helped (maybe the compiler inlined types after compilation or so).

**Comment by timocov** [comment]
The fix has been [published in 9.4.0 version](https://github.com/timocov/dts-bundle-generator/releases/tag/v9.4.0).

**Pull request merged**
