### PR TITLE
Added checking that node is exported in `export default` ES6 style

### LINKED ISSUE #17: `export default Name;` is not handled correctly
**Code:**
```ts
class MyClass {}
export default MyClass;
```

**Actual output:**
```ts
export declare class MyClass {
}
export default MyClass;
```

**Expected output:**
```ts
declare class MyClass {
}
export default MyClass;
```

### PR DESCRIPTION
**Pull request by timocov**
Fixes #17

(the branch from #60)

### CODE REVIEW

**Comment by bigopon** [comment]
@timocov Hi, how do I try this out? It fails when I tried to install from `#fix17`

**Comment by timocov** [comment]
Hi.

> It fails when I tried to install from 

@bigopon how did you do this?

Try to checkout `fix17` branch, then `npm install`, `npm run prepare-release` and then run `./dist/bin/dts-bundle-generator.js` instead of `dts-bundle-generator`.

**Comment by bigopon** [comment]
oh well, I was hoping that I can avoid that. Will try

**Comment by timocov** [comment]
Hi @bigopon! I'm going to merge this PR. Did you have any issues with this changes?

**Comment by bigopon** [comment]
@timocov Just tried it, I think the path to bin is wrong. It should be `dist/bin/dts-bundle-genetaror.js`

**Comment by bigopon** [comment]
What I did:
```
git clone https://github.com/timocov/dts-bundle-genetaror.git
git checkout -b fix17 origin/fix17
cd dts-bundle-generator
npm install
npm run prepare-release

cd ../
mkdir testapp
cd testapp
npm init -y
npm i i18next @types/i18next ../dts-bundle-generator
```

then create `src/i18n.ts` with following content:
```ts
import * as i18next from "i18next";

export class I18N {
  constructor(config: i18next.InitOptions) {

  }
}
```
and change `"test"` script in `package.json` to:
```json
"test": "dts-bundle-generator -o dist/test.d.ts src/i18n.ts"
```
it produced:
```ts
/// <reference types="i18next" />

export declare class I18N {
	constructor(config: i18next.InitOptions);
}
```

Which should be correct, but not sure why ts reported it could find namespace i18next. Would be nice if the import statement could be carried over.

**Comment by timocov** [comment]
> Would be nice if the import statement could be carried over.

By default all types from `@types` directory are added to bundle as `/// <reference types="" />` directive. If you want to import it via `import` statement, you need to pass `--external-imports` option with value `i18next`.

But for now `dts-bundle-generator` isn't able to handle `import * as name` statement (see [2nd limitation](https://github.com/timocov/dts-bundle-generator#known-limitations)). I believe it can be fixed in #59.

In this case I would suggest you use `import { InitOptions } from 'i18next';` instead of `import * as i18next` and provide `--external-imports` option.

But anyway it seems that this PR fix the main problem and we can merge it. Thanks!

**Comment by timocov** [comment]
Please create another issue for that - it seems that problem is not related to this one. Also, please refer to #59 there.

**Pull request merged**
